version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.6
    ports:
    - "8080:8080"
    - "80:8080"
    restart: always
    environment:
      # database url to connect
      HASURA_GRAPHQL_DATABASE_URL: ${DATABASE_URL}
      # enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set "false" to disable console
      ## uncomment next line to set an admin secret key
      HASURA_GRAPHQL_ADMIN_SECRET: myonrrsecretkey
      